server/config/routes.rb
Rails.application.routes.draw do
  resources :pn_jp_words

  resources :messages

  resources :users, :only => [:index, :show]
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  namespace :admin do
    resources :messages
  end

  namespace :api do
    namespace :v1 do
      resources :messages, :only => [:index, :show, :create, :destroy]
      resources :users, :only => [:index, :show, :create]
    end
  end
end

server/app/models/pn_jp_word.rb
class PnJpWord < ActiveRecord::Base
end

server/app/controllers/pn_jp_words_controller.rb
class PnJpWordsController < ApplicationController
  before_action :set_pn_jp_word, only: [:show, :edit, :update, :destroy]

  # GET /pn_jp_words
  # GET /pn_jp_words.json
  def index
    @pn_jp_words = PnJpWord.all
  end

  # GET /pn_jp_words/1
  # GET /pn_jp_words/1.json
  def show
  end

  # GET /pn_jp_words/new
  def new
    @pn_jp_word = PnJpWord.new
  end

  # GET /pn_jp_words/1/edit
  def edit
  end

  # POST /pn_jp_words
  # POST /pn_jp_words.json
  def create
    @pn_jp_word = PnJpWord.new(pn_jp_word_params)

    respond_to do |format|
      if @pn_jp_word.save
        format.html { redirect_to @pn_jp_word, notice: 'Pn jp word was successfully created.' }
        format.json { render :show, status: :created, location: @pn_jp_word }
      else
        format.html { render :new }
        format.json { render json: @pn_jp_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pn_jp_words/1
  # PATCH/PUT /pn_jp_words/1.json
  def update
    respond_to do |format|
      if @pn_jp_word.update(pn_jp_word_params)
        format.html { redirect_to @pn_jp_word, notice: 'Pn jp word was successfully updated.' }
        format.json { render :show, status: :ok, location: @pn_jp_word }
      else
        format.html { render :edit }
        format.json { render json: @pn_jp_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pn_jp_words/1
  # DELETE /pn_jp_words/1.json
  def destroy
    @pn_jp_word.destroy
    respond_to do |format|
      format.html { redirect_to pn_jp_words_url, notice: 'Pn jp word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pn_jp_word
      @pn_jp_word = PnJpWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pn_jp_word_params
      params.require(:pn_jp_word).permit(:word, :kana, :pos, :value)
    end
end

server/app/helpers/pn_jp_words_helper.rb
module PnJpWordsHelper
end

server/app/views/pn_jp_words/_form.html.erb
<%= form_for(@pn_jp_word) do |f| %>
  <% if @pn_jp_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pn_jp_word.errors.count, "error") %> prohibited this pn_jp_word from being saved:</h2>

      <ul>
      <% @pn_jp_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :kana %><br>
    <%= f.text_field :kana %>
  </div>
  <div class="field">
    <%= f.label :pos %><br>
    <%= f.text_field :pos %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/pn_jp_words/edit.html.erb
<h1>Editing pn_jp_word</h1>

<%= render 'form' %>

<%= link_to 'Show', @pn_jp_word %> |
<%= link_to 'Back', pn_jp_words_path %>

server/app/views/pn_jp_words/index.html.erb
<h1>Listing pn_jp_words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Kana</th>
      <th>Pos</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pn_jp_words.each do |pn_jp_word| %>
      <tr>
        <td><%= pn_jp_word.word %></td>
        <td><%= pn_jp_word.kana %></td>
        <td><%= pn_jp_word.pos %></td>
        <td><%= pn_jp_word.value %></td>
        <td><%= link_to 'Show', pn_jp_word %></td>
        <td><%= link_to 'Edit', edit_pn_jp_word_path(pn_jp_word) %></td>
        <td><%= link_to 'Destroy', pn_jp_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pn jp word', new_pn_jp_word_path %>

server/app/views/pn_jp_words/new.html.erb
<h1>New pn_jp_word</h1>

<%= render 'form' %>

<%= link_to 'Back', pn_jp_words_path %>

server/app/views/pn_jp_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @pn_jp_word.word %>
</p>

<p>
  <strong>Kana:</strong>
  <%= @pn_jp_word.kana %>
</p>

<p>
  <strong>Pos:</strong>
  <%= @pn_jp_word.pos %>
</p>

<p>
  <strong>Value:</strong>
  <%= @pn_jp_word.value %>
</p>

<%= link_to 'Edit', edit_pn_jp_word_path(@pn_jp_word) %> |
<%= link_to 'Back', pn_jp_words_path %>