server/config/routes.rb
Rails.application.routes.draw do
  resources :pn_jp_words

  resources :messages

  resources :users, :only => [:index, :show]
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  namespace :admin do
    resources :messages
  end

  namespace :api do
    namespace :v1 do
      resources :messages, :only => [:index, :show, :create, :destroy]
      resources :users, :only => [:index, :show, :create]
    end
  end
end

server/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>
<li><%= link_to 'Messages', messages_path %></li>
<li><%= link_to 'Compose', new_message_path %></li>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pigeon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div><%= msg %></div>
  <% end %>
<% end %>

<%= render 'layouts/navigation_links' %>

<%= yield %>

</body>
</html>